<a href="https://colab.research.google.com/github/Spandana2704/DL/blob/main/DL2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def AND(x1,x2):
    w1=1
    w2=1
    b=-1.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(AND(x1,x2),end=" ")

0 0 0 1

In [ ]:
def OR(x1,x2):
    w1=1
    w2=1
    b=-0.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(OR(x1,x2),end=" ")

0 1 1 1

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=-1
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 1 1 1

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=1
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

1 1 1 1

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=-2
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 0 0 1

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=-2.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 0 0 0

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=-1.8
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 0 0 1

In [ ]:
def XOR(x1,x2):
    w1=1
    w2=1
    b=-0.6
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 1 1 1

In [ ]:
def AND(x1,x2):
    w1=1
    w2=1
    b=-1.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

def OR(x1,x2):
    w1=1
    w2=1
    b=-0.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

def NAND(x1,x2):
    w1=-1
    w2=-1
    b=1.5
    activation=w1*x1+w1*x2+b
    if activation>=0:
        return 1
    else:
        return 0

def XOR(x1,x2):
    first_layer_op=NAND(x1,x2)
    sec_layer_op=OR(x1,x2)
    op=AND(first_layer_op,sec_layer_op)
    return op

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(XOR(x1,x2),end=" ")

0 1 1 0

In [ ]:
def NXOR(x1,x2):
    first_layer_op=NAND(x1,x2)
    sec_layer_op=OR(x1,x2)
    op=NAND(first_layer_op,sec_layer_op)
    return op

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(NXOR(x1,x2),end=" ")

1 0 0 1

In [ ]:
def perceptron(x1,x2):
    w1=4
    w2=0.5
    b=-0.1
    activation=w1*x1+w1*x2+b
    print("activation:",activation,end=" ")
    if activation>=0:
        return 1
    else:
        return 0

x=[(0,0),(0,1),(1,0),(1,1)]
for x1,x2 in x:
    print(perceptron(x1,x2),end="\n")

activation: -0.1 0
activation: 3.9 1
activation: 3.9 1
activation: 7.9 1

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Movie - Sheet1.csv")

In [ ]:
df

,Is actor Matt Damon present,Is the genre Thriller,Is the director Christopher Nolan,IMDb rating,output
0,1,0,1,0.88,1
1,0,1,0,0.54,0
2,0,0,1,0.69,1
3,1,0,0,0.78,0
4,1,1,1,0.45,0
5,0,1,1,0.65,1
6,1,0,0,0.54,0
7,0,1,1,0.90,1
8,0,0,1,0.63,0
9,1,1,0,0.71,0

In [ ]:
x=df.drop(["output"],axis=1)
y=df["output"]

In [ ]:
def movie(x1,x2,x3,x4):
    w1=1
    w2=0.5
    w3=-1
    w4=1
    b=-0.5
    activation=w1*x1+w2*x2+w3*x3+w4*x4+b
    if activation>=0:
        return 1
    else:
        return 0

for x1,x2,x3,x4 in x.values:
    print(movie(x1,x2,x3,x4))

1
1
0
1
1
0
1
0
0
1

In [ ]:
y

0    1
1    0
2    1
3    0
4    0
5    1
6    0
7    1
8    0
9    0
Name: output, dtype: int64